# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('StudentApp', '0002_auto_20160928_1227'),
        ('CompApp', '0005_auto_20161011_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossCountryResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('house_points', models.IntegerField()),
                ('event',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_country_result',
                                   to='CompApp.CrossCountry')),
                ('student',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_result',
                                   to='StudentApp.Student')),
            ],
        ),
    ]
