# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-29 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('CompApp', '0007_auto_20161011_0957'),
        ('StudentApp', '0002_auto_20160928_1227'),
        ('ResultApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldEventResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('house_points', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_result',
                                            to='CompApp.FieldEvent')),
                ('student',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_field_result',
                                   to='StudentApp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='SwimmingRelayResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('house_points', models.IntegerField()),
                ('event',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swim_relay_result',
                                   to='CompApp.SwimmingRelay')),
                ('house',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_swim_relay_result',
                                   to='StudentApp.House')),
            ],
        ),
        migrations.CreateModel(
            name='SwimmingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('house_points', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swim_result',
                                            to='CompApp.Swimming')),
                ('student',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_swim_result',
                                   to='StudentApp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='TrackEventResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('house_points', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_result',
                                            to='CompApp.TrackEvent')),
                ('student',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_track_result',
                                   to='StudentApp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='TrackRelayResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('house_points', models.IntegerField()),
                ('event',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_relay_result',
                                   to='CompApp.TrackRelay')),
                ('house',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_track_relay_result',
                                   to='StudentApp.House')),
            ],
        ),
        migrations.RemoveField(
            model_name='crosscountryresult',
            name='event',
        ),
        migrations.RemoveField(
            model_name='crosscountryresult',
            name='student',
        ),
        migrations.DeleteModel(
            name='CrossCountryResult',
        ),
    ]
