# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-24 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('StudentApp', '0002_auto_20160928_1227'),
        ('ResultApp', '0002_auto_20170329_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimmingresult',
            name='house',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='house_swim_result', to='StudentApp.House'),
            preserve_default=False,
        ),
    ]
