# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-26 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultApp', '0006_auto_20170426_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimmingresult',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
