# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-30 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultApp', '0008_crosscountryresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimmingrelayresult',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
