# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-02 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultApp', '0009_auto_20170430_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crosscountryresult',
            options={'ordering': ['-house_points']},
        ),
        migrations.AlterModelOptions(
            name='fieldeventresult',
            options={'ordering': ['-house_points']},
        ),
        migrations.AlterModelOptions(
            name='swimmingrelayresult',
            options={'ordering': ['-house_points']},
        ),
        migrations.AlterModelOptions(
            name='swimmingresult',
            options={'ordering': ['-house_points']},
        ),
        migrations.AlterModelOptions(
            name='trackeventresult',
            options={'ordering': ['-house_points']},
        ),
        migrations.AlterModelOptions(
            name='trackrelayresult',
            options={'ordering': ['-house_points']},
        ),
        migrations.AlterField(
            model_name='swimmingrelayresult',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='swimmingresult',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackeventresult',
            name='time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='trackrelayresult',
            name='time',
            field=models.DurationField(),
        ),
    ]
