# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-03 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResultApp', '0010_auto_20170702_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackeventresult',
            options={'ordering': ['time']},
        ),
    ]
