# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='slug',
            field=models.SlugField(default='the-gregg-school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(default='the-gregg-school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses',
                                    to='StudentApp.School'),
        ),
        migrations.AlterField(
            model_name='student',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students',
                                    to='StudentApp.House'),
        ),
    ]
