# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=200)),
                ('comp_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CrossCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_country_event',
                                   to='CompApp.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='FieldEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(
                    choices=[('HJ', 'High Jump'), ('LJ', 'Long Jump'), ('TJ', 'Triple Jump'), ('CB', 'Cricket Ball'),
                             ('RB', 'Rounders Ball'), ('SP', 'Shot Put'), ('DI', 'Discus'), ('JA', 'Javelin'),
                             ('PV', 'Pole Vault')], default=None, max_length=2)),
                ('competition',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_event',
                                   to='CompApp.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='Swimming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stroke', models.CharField(
                    choices=[('FC', 'Front Crawl'), ('BS', 'Breast Stroke'), ('BA', 'Backstroke'), ('BU', 'Butterfly'),
                             ('FR', 'Freestyle')], default='FR', max_length=2)),
                ('distance_in_meters', models.IntegerField(max_length=2)),
                ('competition',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swimming_event',
                                   to='CompApp.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='SwimmingRelay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_students', models.IntegerField(max_length=1)),
                ('distance_per_student', models.IntegerField(max_length=2)),
                ('stroke',
                 models.CharField(choices=[('FR', 'Freestyle'), ('ME', 'Medley'), ('SQ', 'Squadron')], default='FR',
                                  max_length=2)),
                ('competition',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swimming_relay',
                                   to='CompApp.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='TrackEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_in_meters', models.IntegerField(max_length=4)),
                ('competition',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_event',
                                   to='CompApp.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='TrackRelay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_students', models.IntegerField(max_length=1)),
                ('distance_per_student', models.IntegerField(max_length=4)),
                ('competition',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_relay',
                                   to='CompApp.Competition')),
            ],
        ),
    ]
