# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimming',
            name='distance_in_meters',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='swimmingrelay',
            name='distance_per_student',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='swimmingrelay',
            name='number_of_students',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trackevent',
            name='distance_in_meters',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trackrelay',
            name='distance_per_student',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trackrelay',
            name='number_of_students',
            field=models.IntegerField(),
        ),
    ]
