# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompApp', '0002_auto_20160914_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='comp_date',
            new_name='competition_date',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='comp_name',
            new_name='competition_name',
        ),
    ]
