# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('CompApp', '0003_auto_20160914_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosscountry',
            name='gender',
            field=models.CharField(choices=[('B', 'Boys'), ('G', 'Girls')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='crosscountry',
            name='year_group',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fieldevent',
            name='gender',
            field=models.CharField(choices=[('B', 'Boys'), ('G', 'Girls')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='fieldevent',
            name='year_group',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='swimming',
            name='gender',
            field=models.CharField(choices=[('B', 'Boys'), ('G', 'Girls')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='swimming',
            name='year_group',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='swimmingrelay',
            name='gender',
            field=models.CharField(choices=[('B', 'Boys'), ('G', 'Girls')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='swimmingrelay',
            name='year_group',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trackevent',
            name='gender',
            field=models.CharField(choices=[('B', 'Boys'), ('G', 'Girls')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='trackevent',
            name='year_group',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trackrelay',
            name='gender',
            field=models.CharField(choices=[('B', 'Boys'), ('G', 'Girls')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='trackrelay',
            name='year_group',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='swimming',
            name='stroke',
            field=models.CharField(
                choices=[('FC', 'Front Crawl'), ('BS', 'Breast Stroke'), ('BA', 'Backstroke'), ('BU', 'Butterfly'),
                         ('FR', 'Freestyle'), ('SQ', 'Squadron')], default='FR', max_length=2),
        ),
        migrations.AlterField(
            model_name='swimmingrelay',
            name='stroke',
            field=models.CharField(choices=[('FR', 'Freestyle'), ('ME', 'Medley')], default='FR', max_length=2),
        ),
    ]
