# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompApp', '0005_auto_20161011_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
