# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompApp', '0006_competition_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='slug',
            field=models.SlugField(default='competition_name'),
        ),
    ]
