# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-26 15:44
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ('CompApp', '0008_auto_20170426_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosscountry',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False,
                                                            populate_from=['competition', 'year_group', 'gender']),
        ),
        migrations.AlterField(
            model_name='fieldevent',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False,
                                                            populate_from=['competition', 'year_group', 'gender']),
        ),
        migrations.AlterField(
            model_name='swimming',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False,
                                                            populate_from=['competition', 'year_group', 'gender']),
        ),
        migrations.AlterField(
            model_name='swimmingrelay',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False,
                                                            populate_from=['competition', 'year_group', 'gender']),
        ),
        migrations.AlterField(
            model_name='trackevent',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False,
                                                            populate_from=['competition', 'year_group', 'gender']),
        ),
        migrations.AlterField(
            model_name='trackrelay',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False,
                                                            populate_from=['competition', 'year_group', 'gender']),
        ),
    ]
