# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-01 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompApp', '0010_auto_20170430_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crosscountry',
            name='gender',
            field=models.CharField(choices=[('M', 'Boys'), ('F', 'Girls')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='crosscountry',
            name='year_group',
            field=models.CharField(choices=[('07', 'Year 7'), ('08', 'Year 8'), ('09', 'Year 9'), ('10', 'Year 10'), ('11', 'Year 11')], default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='fieldevent',
            name='gender',
            field=models.CharField(choices=[('M', 'Boys'), ('F', 'Girls')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='fieldevent',
            name='year_group',
            field=models.CharField(choices=[('07', 'Year 7'), ('08', 'Year 8'), ('09', 'Year 9'), ('10', 'Year 10'), ('11', 'Year 11')], default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='swimming',
            name='gender',
            field=models.CharField(choices=[('M', 'Boys'), ('F', 'Girls')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='swimming',
            name='year_group',
            field=models.CharField(choices=[('07', 'Year 7'), ('08', 'Year 8'), ('09', 'Year 9'), ('10', 'Year 10'), ('11', 'Year 11')], default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='swimmingrelay',
            name='gender',
            field=models.CharField(choices=[('M', 'Boys'), ('F', 'Girls')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='swimmingrelay',
            name='year_group',
            field=models.CharField(choices=[('07', 'Year 7'), ('08', 'Year 8'), ('09', 'Year 9'), ('10', 'Year 10'), ('11', 'Year 11')], default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='trackevent',
            name='gender',
            field=models.CharField(choices=[('M', 'Boys'), ('F', 'Girls')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='trackevent',
            name='year_group',
            field=models.CharField(choices=[('07', 'Year 7'), ('08', 'Year 8'), ('09', 'Year 9'), ('10', 'Year 10'), ('11', 'Year 11')], default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='trackrelay',
            name='gender',
            field=models.CharField(choices=[('M', 'Boys'), ('F', 'Girls')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='trackrelay',
            name='year_group',
            field=models.CharField(choices=[('07', 'Year 7'), ('08', 'Year 8'), ('09', 'Year 9'), ('10', 'Year 10'), ('11', 'Year 11')], default=None, max_length=2),
        ),
    ]
