# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-25 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompApp', '0012_auto_20170501_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackevent',
            name='track_choice',
            field=models.CharField(choices=[('Heats', 'Heats'), ('Final', 'Final')], default='Final', max_length=5),
        ),
    ]
