# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-03 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompApp', '0013_trackevent_track_choice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['-competition_date']},
        ),
    ]
