# Generated by Django 2.0.6 on 2018-06-29 20:50

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('CompApp', '0014_auto_20170703_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crosscountry',
            options={'ordering': ['year_group', 'gender']},
        ),
        migrations.AlterModelOptions(
            name='fieldevent',
            options={'ordering': ['year_group', 'gender']},
        ),
        migrations.AlterModelOptions(
            name='swimming',
            options={'ordering': ['year_group', 'gender']},
        ),
        migrations.AlterModelOptions(
            name='swimmingrelay',
            options={'ordering': ['year_group', 'gender']},
        ),
        migrations.AlterModelOptions(
            name='trackevent',
            options={'ordering': ['year_group', 'gender']},
        ),
        migrations.AlterModelOptions(
            name='trackrelay',
            options={'ordering': ['year_group', 'gender']},
        ),
        migrations.AddField(
            model_name='competition',
            name='junior_year_groups',
            field=models.CharField(default='7,8', max_length=30, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
